language: go

go:
- 1.13

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.22.2/install.sh | sh -s -- -b $(go env GOPATH)/bin

stages:
  - build
  - build_package
  - test
  - test_required_linters
  - test_optional_linters

build: &build
  stage: build
  install: skip
  if: tag IS NOT present
  script: make bin

build_package: &build_package
  stage: build_package
  install: skip
  if: tag IS present
  script: make
  deploy:
    - provider: releases
      token:
        secure: $GITHUB_API_KEY
      file_glob: true
      file: package-*.tar.gz
      skip_cleanup: true
      on:
        all_branches: true

jobs:
  include:
    - <<: *build
      os: linux
    
    - <<: *build
      os: windows

    - <<: *build
      os: osx

    - <<: *build_package
      os: linux

    - <<: *build_package
      os: windows

    - <<: *build_package
      os: osx

    - stage: test
      install: skip
      script:
        - go test -coverprofile=coverage.out -mod=vendor ./cmd/... ./pkg/...
        - go tool cover -func=coverage.out
      os: linux

    - stage: test_required_linters
      script: golangci-lint run --config CI/golangci_required_linters.yml cmd/... pkg/...
      os: linux

    - stage: test_optional_linters
      script: golangci-lint run --config CI/golangci_optional_linters.yml cmd/... pkg/...
      os: linux
